// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXp04-CG99xsUiJEVCUa17QUQ3rvit8c',
    appId: '1:722538088599:web:1aadeac175b5cb41a981d2',
    messagingSenderId: '722538088599',
    projectId: 'auth-flutter-26262',
    authDomain: 'auth-flutter-26262.firebaseapp.com',
    storageBucket: 'auth-flutter-26262.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeys-42ay6JjMcbyd3fiv4RrtbrJh0bGg',
    appId: '1:722538088599:android:246f77aa74ccdb6ca981d2',
    messagingSenderId: '722538088599',
    projectId: 'auth-flutter-26262',
    storageBucket: 'auth-flutter-26262.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLCR3SH44LTexPn0Hu0UoO9ls4ulU7XFM',
    appId: '1:722538088599:ios:d983cc2b47844d1fa981d2',
    messagingSenderId: '722538088599',
    projectId: 'auth-flutter-26262',
    storageBucket: 'auth-flutter-26262.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLCR3SH44LTexPn0Hu0UoO9ls4ulU7XFM',
    appId: '1:722538088599:ios:67304cd10675c359a981d2',
    messagingSenderId: '722538088599',
    projectId: 'auth-flutter-26262',
    storageBucket: 'auth-flutter-26262.appspot.com',
    iosBundleId: 'com.example.authFirebase.RunnerTests',
  );
}
